# canvas
# Source: https://github.com/DMontgomery40/mcp-canvas-lms
# Toolathlon Version: https://github.com/lockon-n/mcp-canvas-lms
type: stdio
name: canvas
params:
  command: npx
  args:
    - "-y"
    - "canvas-mcp-server"
  env:
    CANVAS_API_TOKEN: "${token.canvas_api_token}"
    CANVAS_DOMAIN: "${token.canvas_domain}"
    # skip self-signed certificate detection, set NODE_TLS_REJECT_UNAUTHORIZED=0
    NODE_TLS_REJECT_UNAUTHORIZED: "0"
    # if you don't need to load custom CA certificates, you can comment out the following line
    # NODE_EXTRA_CA_CERTS: "deployment/canvas/logs/cert.pem"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 10
cache_tools_list: true