# emails
# Source: https://github.com/lockon-n/emails-mcp
# Toolathlon Version: The same
type: stdio
name: emails
params:
  command: uvx
  args:
    - "emails-mcp"
    - "--attachment_download_path"
    - "${agent_workspace}/emails_download"
    - "--attachment_upload_path"
    - "${agent_workspace}"
    - "--email_export_path"
    - "${agent_workspace}/emails_export"
    - "--config_file"
    - "${token.emails_config_file}"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 120
cache_tools_list: true
