# file system server - for reading and writing files
# Source: https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem
# Toolathlon Version: The same
type: stdio
name: filesystem
params:
  command: npx
  args:
    - "-y"
    - "@modelcontextprotocol/server-filesystem"
    - "${agent_workspace}"  # only allow reading and writing files in this directory
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 300
cache_tools_list: true