# Google Forms
# Source: https://github.com/matteoantoci/google-forms-mcp
# Toolathlon Version: The same
type: stdio
name: google_forms
params:
  command: node
  args:
    - "${local_servers_paths}/google-forms-mcp/build/index.js"
  env:
    GOOGLE_CLIENT_ID: "${token.google_client_id}"
    GOOGLE_CLIENT_SECRET: "${token.google_client_secret}"
    GOOGLE_REFRESH_TOKEN: "${token.google_refresh_token}"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 20
cache_tools_list: true