# Google Map
# Source: https://github.com/modelcontextprotocol/servers-archived/tree/main/src/google-maps
# Toolathlon Version: The same
type: stdio
name: google_map
params:
  command: npx
  args:
    - "-y"
    - "@modelcontextprotocol/server-google-maps"
  env:
    GOOGLE_MAPS_API_KEY: "${token.google_cloud_console_api_key}"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 10
cache_tools_list: true