# Google Sheet
# Source: https://github.com/xing5/mcp-google-sheets
# Toolathlon Version: The same
type: stdio
name: google_sheet
params:
  command: uvx
  args:
    - "mcp-google-sheets"
  env:
    CREDENTIALS_PATH: "${token.google_oauth2_credentials_path}"
    TOKEN_PATH: "${token.google_oauth2_token_path}"
    DRIVE_FOLDER_ID: "${token.google_sheets_folder_id}"
  # cwd: "${agent_workspace}" # do not add this for compatibility
client_session_timeout_seconds: 60
cache_tools_list: true