# Knowledge Graph Memory
# Source: https://github.com/modelcontextprotocol/servers/tree/main/src/memory
# Toolathlon Version: The same
type: stdio
name: memory
params:
  command: npx
  args:
    - "-y"
    - "@modelcontextprotocol/server-memory"
  env:
    MEMORY_FILE_PATH: "${agent_workspace}/memory/memory.json"
  cwd: "${agent_workspace}"
client_session_timeout_seconds: 100
cache_tools_list: true
# this server will read/write the memory.json